alphasights/ember-scrollable

addon/components/ember-scrollable.js

`didInsertElement()` was in the ember-scrollable component twice and caused my PhantomJS test-runner to complain.

Removed duplicate didInsertElement

---

addon/classes/scrollable.js

Hello. 
Thanks for great add-on.
For my collection of > 1000 items calculations of scrollbar not working correctly.
scrollbarRation is less than 0.001 and scrollbar handle not even visible.
I made some changes to calculation of scrollbar handle height, so I set a minimum value of scrollbar ratio so handle has some height.

Check scrollbar height for large collections

---

addon/components/ember-scrollable.js
addon/templates/components/ember-scrollable.hbs

Add action and hash to manually scroll the scrollable area to top.
Initiated by https://github.com/alphasights/ember-scrollable/issues/15.

Add scrollTop action which can be triggered from outside

---

README.md
addon/components/ember-scrollable.js
tests/acceptance/index-test.js
tests/dummy/app/templates/index.hbs

Closes #24 and #15.
This PR adds the property `scrollTo` and the action `onScroll`.
Example usage:
```hbs
targetScrollOffset:  {{input value=targetScrollOffset type="number" min=0 step=10 max=400}}
currentScrollOffset: {{currentScrollOffset}} px
{{#ember-scrollable
scrollTo=targetScrollOffset
onScroll=(action (mut currentScrollOffset))
}}
...
{{/ember-scrollable}}
```
...expects a Number or String that can be parsed as a Number. It then sets the `scrollTop` (or `scrollLeft`) value of the `scrollContentElement` in accordance, whenever `scrollTo` is updated.
...expects an action that is called with the current `scrollOffset` (either `scrollTop` or `scrollLeft`) and the original scroll `event`.
`onScroll` is debounced by 100 ms, just as `onScrolledToBottom` is.

scrollTo and onScoll

---

addon/components/ember-scrollable.js

As noted in https://github.com/alphasights/ember-scrollable/pull/25#discussion_r84637226, if the component is initialized with a `scrollTo` attribute, `scrollToPosition` is triggered before the component is rendered.
This PR fixes this.

Fix scroll before render

---

addon/components/ember-scrollable.js

Before this change it was possible for `resizeScrollbar` to bomb out if it was called when in the `isDestroyed` state. It is possible for the component to both be `isDestroyed` and have a `scrollbar` still.
This is similar to: https://github.com/alphasights/ember-scrollable/commit/f404e12468a9d18667a8c9712643ff57d4dee450

Guards against `set` being called on a destroyed object.

---

package.json

Tested the latest commit and saw this error:
Uncaught Error: Could not find module `ember-lifeline/mixins/dom` imported from `ember-scrollable/components/ember-scrollable`

Move 'ember-lifeline' into dependencies

---

addon/components/ember-scrollable.js
package.json
tests/dummy/app/router.js
tests/dummy/app/templates/cookbook.hbs
tests/dummy/app/templates/extra.hbs
tests/dummy/app/templates/index.hbs

closes https://github.com/alphasights/ember-scrollable/issues/39 
cc @dknutsen
Added an `cookbook` demo page with a draggable element inside of it, also an example of how you would synchronize two scollbars, as I thought it might be helpful.

Fixing #39: Allowing to draggable elments inside of ember-scrollable

---

addon/components/ember-scrollable.js
addon/components/ember-scrollbar.js
package.json
tests/acceptance/index-test.js
tests/dummy/app/templates/index.hbs
tests/integration/components/ember-scrollbar-test.js

cc @offirgolan @bugduino  closes https://github.com/offirgolan/ember-light-table/issues/323
I merged https://github.com/alphasights/ember-scrollable/pull/57 into this branch because I wanted to use `ember-native-dom-helpers` and didn't want to get conflicts...
I'll leave #57 open to figure out the aynsc scroll stuff.

Fix: Scrollbar visible when content changes to no longer have overflow

---

addon/components/ember-scrollbar.js
package.json
tests/integration/components/ember-scrollbar-test.js

Also improved the weird naming surrounding the first argument to `jumpTo` and added docs.
related:
@cibernox -- I couldn't get the equivalent of `this.$(elem).scrollTop()` or `.scrollLeft()` to work.
It seems like `scrollTop()` simply modifies the `scrollTop` property on the elment, which generates an async event that doesn't contain much info about the scroll, besides that it did (and the target element, that has the mutated property already). I haven't been able to get my tests to wait for the scroll event resolve and callback, etc.
because of this we have some nastiness in the form of arbitrary delay times..  https://github.com/alphasights/ember-scrollable/blob/master/tests/integration/components/scroll-content-element-test.js#L122
<details>
<summary> Dev console images of scroll …

Leverage ember-native-dom-helpers for better interaction testing

---

addon/components/ember-scrollable.js

The current `onScroll` method is not sufficient in the
ember-scrollable that supports both horizontal and vertical
scrolling since there is no way of determining what direction
was scrolled without forcing clients to keeping state and detect
the scroll direction (something that is already done by ember-scrollable).
As such, we should deprecate the old usage, and add new callbacks.

Adding `onScrollToX` and `onScrollToY` callbacks.

---

addon/components/scroll-content-element.js
addon/util/number.js

supercedes https://github.com/alphasights/ember-scrollable/pull/51 because EmberConf
closes https://github.com/alphasights/ember-scrollable/issues/67  and https://github.com/alphasights/ember-scrollable/issues/50
alternative to https://github.com/alphasights/ember-scrollable/pull/68

Creating Number to polyfill

---

addon/components/ember-scrollable.js
addon/services/scrollbar-thickness.js
app/services/scrollbar-thickness.js

Fixes #64
Scrollbar width is still calculated repeatedly; once for every component.

calculate scrollbar width correctly

---

addon/components/ember-scrollable.js
addon/components/ember-scrollbar.js
addon/components/scroll-content-element.js
addon/util/css.js

cc @offirgolan 
Closes https://github.com/alphasights/ember-scrollable/issues/59
>Adding event listeners to window object
Instead of document.body, this allows for the mousemove being tracked even
outside of browser window, similar to how native browsers work.
If you drag and move the mouse outside of the browser window,
the scrollbar should still scroll until you mouseup
@nem-jmalatin let me know if this behaves as you expect.

Mouse Events on Window Instead of DOM

---

addon/components/ember-scrollable.js
tests/unit/components/ember-scrollable-test.js

I ran into this bug while working for a client who is using `ember-light-table`.  We sometimes tear down the table due to user interaction, which can end up hitting this `ember-scrollable` bug.
If the `ember-scrollable` component is torn down mid-way through the `createScrollbarAndShowIfNecessary`, https://github.com/alphasights/ember-scrollable/blob/master/addon/components/ember-scrollable.js#L250 blows up.  It's expecting an array to be returned from `createScrollbar` at all times, but we were returning an `undefined` value instead.
Thanks for all your work on this! ❤️

Fix a return value when our component has been torn down

---

addon/components/ember-scrollable.js
tests/acceptance/index-test.js
tests/dummy/app/templates/cookbook.hbs
tests/dummy/app/templates/index.hbs
tests/integration/components/scroll-content-element-test.js

- changed the usage of `scrollContentSize` to match that of the drag, which was `contentSize`
- fixed deprecation warnings in our own repo, because it's sad when you trigger your own deprecations

Friendly cleanup

---

addon/styles/addon.css

remove all ::scrollbar pseudo selectors

---

addon/components/ember-scrollable.js

When using mousewheel to trigger scroll we need to
make sure we're updating the scrollToX and scrollToY
properties. This was causing a "jumping" around issue
when then using the horizontal scrollbar to scroll
horizontallly after scrolling vertically.
Fixes #72

Fixng scrollbar jumping around bug

---

addon/components/ember-scrollable.js
addon/components/scroll-content-element.js

`callback` is bound to component context here: https://github.com/rwjblue/ember-lifeline/blob/v2.0.0/addon/mixins/dom.js#L90

avoid creating extra closure

---

addon/components/ember-scrollbar.js
addon/templates/components/ember-scrollable.hbs
tests/integration/components/ember-scrollbar-test.js

Hey, this is a sort of continuation of #83. I've tried to demo what's happening [here](https://github.com/piotrpalek/scrollable-example).
The issue is that ember-scrollable updates the `mouseOffset` argument at nearly 60fps. In certain conditions (I've noticed it mainly in the usage of `ember-light-table` but there could be others) it means that it triggers re-renders constantly when moving the mouse anywhere over the window. This causes severe performance issues if you for eg. use a `didRender` hook which does some work, since it's constantly triggered.
This PR fixes the issue by removing the passing of `mouseOffset` to the `ember-scrollable` component and instead directly triggers the function which does the main work.

Fix lingering performance issues

---

package.json

Updated ember-element-resize-detector version to remove deprecation warnings about `sendAction`

Updated ember-element-resize-detector version

---

yarn.lock

Updates `morgan` to avoid the possibility of [arbitrary code execution](https://nvd.nist.gov/vuln/detail/CVE-2019-5413).

Upgrade morgan to avoid arbitrary commands issue

---

yarn.lock

We're getting lots of security warning from GitHub, but dependabot is not able to fix them automatically. This PR upgrades many yarn dependencies to avoid using versions with known vulnerabilities.

Upgrade all yarn dependencies

---

package.json
tests/dummy/config/optional-features.json

As per #105 this will remove the deprecation warning pending removal of jQuery

Temp deprecation fix add ember jquery to dependencies

---

addon/classes/scrollable.js
addon/components/ember-scrollable.js
addon/components/ember-scrollbar.js
addon/components/scroll-content-element.js
addon/services/scrollbar-thickness.js
addon/util/measurements.js
package.json
tests/integration/components/ember-scrollbar-test.js
tests/integration/components/scroll-content-element-test.js
yarn.lock

note: I am waiting to update the tests [because of](https://github.com/EmberSherpa/ember-element-resize-detector/pull/17)

Remove usages of jQuery

---

addon/components/ember-scrollable.js

Fixes the following deprecation:
```
DEPRECATION: <...@component:ember-scrollable::ember1759>: Using `mouseMove` event handler methods in components has been deprecated. [deprecation id: ember-views.event-dispatcher.mouseenter-leave-move] See https://emberjs.com/deprecations/v3.x#toc_component-mouseenter-leave-move for more details.
```

Fix deprecation warning from use of Ember.Component.mouseMove()
